# Generated by Django 3.1.3 on 2020-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20201110_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
