# Generated by Django 3.1.3 on 2020-11-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20201110_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
